# Use an official Node.js runtime as a parent image
FROM node:16-alpine AS deps

# Set the working directory to /work
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN  npm install

# FROM node:16-alpine AS builder
FROM node:16-alpine AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs

RUN npm run build

ENV NODE_ENV production
# ENV NEXT_TELEMETRY_DISABLED 1

# Expose port 3001 for the Nest.js production server
EXPOSE 3001

ENV PORT 3001

CMD ["npm", "start"]