version: '3.8'
services:
  grow.client:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development