# Use an official Node.js runtime as a parent image
FROM node:16-alpine AS deps

# Set the working directory to /work
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN  npm install --production

# FROM node:16-alpine AS builder
FROM node:16-alpine AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
# USER nextjs

RUN npm run build

# FROM node:16-alpine AS runner
# WORKDIR /app

ENV NODE_ENV production
# ENV NEXT_TELEMETRY_DISABLED 1

# COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
# COPY --from=builder --chown=nextjs:nodejs /app/.env ./
# COPY --from=builder /app/node_modules ./node_modules
# COPY --from=builder /app/package.json ./package.json

# USER nextjs

# Expose port 8080 for the Next.js production server
EXPOSE 8080

ENV PORT 8080

CMD ["npm", "start"]