# Use an official Node.js runtime as a parent image
FROM node:16-alpine AS deps

# Set the working directory to /work
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

FROM node:16-alpine AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Expose port 3000 for the Next.js development server
EXPOSE 3000

# Start the Next.js development server with hot reloading
CMD ["npm", "run", "dev"]